import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import { MapProvider } from "@/providers/map-provider";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lexend.variable} suppressHydrationWarning>
      <body className={lexend.className}>
        <MapProvider>{children}</MapProvider>
      </body>
    </html>
  );
}
