import type { Metadata } from "next";
import { Lexend, Lexend_Deca } from "next/font/google";
import "./globals.css";
import { MapProvider } from "@/providers/map-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { ToastContainer } from "react-toastify";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

const lexendDeca = Lexend_Deca({
  variable: "--font-lexend-deca",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${lexend.className} ${lexendDeca.className}`}>
        <ThemeProvider>
          <MapProvider>{children}</MapProvider>
        </ThemeProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
